%Essential MATLAB by Hahn and Valentine
%
%Maddie C.......................5/18/16
%A rather beautiful fractal picture can be drawn by plotting the points
%(xk,yk) generated by the following difference equations:
%   x(k+1)=y(k)*(1+sin(0.7*x(k))-1.2*sqrt(|x(k)|),
%   y(k+1)=0.21-x(k),
%starting with xo=yo=0. Write a program to draw the picture (plot
%individual points; do not join them).

x(1)=0;
y(1)=0;
for k=1:10000
    x(k+1)=y(k)*(1+sin(0.7*x(k)))-1.2*sqrt(abs(x(k)));
    y(k+1)=0.21-x(k);
end
plot(x,y,'.')